### ISSUE TITLE
Unclear symbol 

### ISSUE THREAD

**Issue by peter-michalski** [caobo1994/FourierSeries#20]
I only see epsilon defined in 5.1.1 (3). Took me some time to find this. The other tests do not have it defined and I do not see it in a symbol table in this document or the CA.

Also, why/how did you set the error values. For example, why is error 10^-6 for 5.1.1 (2)?

**Comment by caobo1994** [comment]
Epsilon is just a symbol that means the acceptable error in testing (floating number variables rarely have no error).

The number 10^-6 is chosen because it is not too large to miss any deliberate error, but large enough to include any computational error.

I guess that these contents shall be added to the document. Any ideas regarding this?

Sent from Mail for Windows 10

From: peter-michalski
Sent: Tuesday, October 29, 2019 18:26
To: caobo1994/FourierSeries
Cc: Subscribed
Subject: [caobo1994/FourierSeries] Unclear symbol (#20)

I only see epsilon defined in 5.1.1 (3). Took me some time to find this. The other tests do not have it defined and I do not see it in a symbol table in this document or the CA.
Also, why/how did you set the error values. For example, why is error 10^-6 for 5.1.1 (2)?

**Comment by peter-michalski** [comment]
Thank you for confirming. I think epsilon may need to be added into the symbol table of the CA for clarity.

Each of the fixed error values that you have chosen for the various experiments could be added (and explained) as assumptions (and perhaps even symbolic parameters) in the CA and then referenced in the VnV

**Comment by caobo1994** [comment]
Actually, I decide not to add them to my CA. The epsilon symbol is totally unrelated to the functions of my library, simply needed for testing.

If I change the value of epsilons here, it will not affect any content in the CA. That is why I think is not related.

Sent from Mail for Windows 10

**Comment by peter-michalski** [comment]
That is a good point. Can you define it in a table in the VnV?
I had to guess that it is error (until I saw it in 5.1.1 (3)). Even though the guess can be fairly well assumed, I'm not sure if it should be remotely vague.
One could argue that this depends on the intended user of the document, but I think being explicitly clear would always be beneficial.

**Comment by caobo1994** [comment]
As I said, I will make a paragraph talking about the tolerance epsilon and its value before the related tests.

Sent from Mail for Windows 10

**Comment by caobo1994** [comment]
Included in a50df1c
