### ISSUE TITLE
5.2.1 input 

### ISSUE THREAD

**Issue by peter-michalski** [caobo1994/FourierSeries#22]
The VnV Checklist states that we are to have specific input. 

"and Ai’s and Bi’s generated from a random
number generator. In this test, this generator is chosen as the uniform
random number generator on [−1.0, 1.0]."

The above quote from your 5.2.1 speed evaluation test means that the test case does not have specific input. While you do provide sufficient instruction for a test, I believe it is important for you to generate these numbers now and place the exact numbers in the test. This was the test is standardized and it is repeated with the same values regardless of who reads the document and implements the test.

Or does the system use a random number generator function itself?

**Comment by caobo1994** [comment]
Really? I need to generate hundreds, even thousands of random numbers right now? I seriously do not believe so. Even though I know that requirement, I still intend to create a random number generator in the code for test, and let it generate test cases for every test. Since it is a test for speed, not for the accuracy of result, the difference in the generated random numbers is not important, as long as they are generated from the same generator each time.

Sent from Mail for Windows 10

From: peter-michalski
Sent: Tuesday, October 29, 2019 19:30
To: caobo1994/FourierSeries
Cc: Subscribed
Subject: [caobo1994/FourierSeries] 5.2.1 input (#22)

The VnV Checklist states that we are to have specific input.
"and Ai’s and Bi’s generated from a random
number generator. In this test, this generator is chosen as the uniform
random number generator on [−1.0, 1.0]."
The above quote from your 5.2.1 speed evaluation test means that the test case does not have specific input. While you do provide sufficient instruction for a test, I believe it is important for you to generate these numbers now and place the exact numbers in the test. This was the test is standardized and it is repeated with the same values regardless of who reads the document and implements the test.

**Comment by peter-michalski** [comment]
I understand now you will provide the random number generator

**Comment by peter-michalski** [comment]
Is there instructions or a name for this generator? If someone else was to look at this VnV to do the test, will they know where to get these numbers?

**Comment by caobo1994** [comment]
Any generator that generates the same distribution of random number works.
Any generator that fits the description will produce the same result.
Testers can choose any one that fits this criteria.

That is the beauty of random numbers. What they actually are is not that
important, as long as they follow the pre-defined distribution, and there
are lots of them.

peter-michalski <notifications@github.com> 于 2019年10月29日周二 19:49写道：

**Comment by peter-michalski** [comment]
Okay. So these numbers will be automatically fed into your system through an interface, or the code  will be adjusted by the tested to use a random generator and format input into the program?

**Comment by caobo1994** [comment]
The test code will generate numbers, form CFS's based on them, and call the
tested function.

peter-michalski <notifications@github.com> 于 2019年10月29日周二 20:03写道：
